### ISSUE TITLE
支持yolov8半监督训练吗

### ISSUE THREAD

**Issue by Bigtuo** [AlibabaResearch/efficientteacher#11]

**Comment by BowieHsu** [comment]
We have implemented a version that is still in testing. Essentially, it just involves adding an additional ssod loss for YOLOv8.

**Comment by Bigtuo** [comment]
那这个v8什么时候会放出来呢，还有你们这些算法，去实现分割功能好修改吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 中午12:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AlibabaResearch/efficientteacher] 支持yolov8半监督训练吗 (Issue #11)




 
We have implemented a version that is still in testing. Essentially, it just involves adding an additional ssod loss for YOLOv8.

**Comment by BowieHsu** [comment]
Hello, due to our limited development resources, I will provide a scheduling update for your two requirements. Currently, we are working on semi-supervised anchor-free detection, as you can see, we have already refactored the main YOLO series solutions into a unified format and are conducting extensive experiments. As for supporting segmentation, our refactoring solution is actually very similar to YOLOv8. You can modify the dataloader to read segmentation data and then reload a segmentation detection head to complete the segmentation training task (these are readily available implementations in YOLOv8, so it shouldn't be too difficult to modify)
Feel free to ask any question!

**Comment by Bigtuo** [comment]
好的，谢谢😊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 中午12:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AlibabaResearch/efficientteacher] 支持yolov8半监督训练吗 (Issue #11)




 
Hello, due to our limited development resources, I will provide a scheduling update for your two requirements. Currently, we are working on semi-supervised anchor-free detection, as you can see, we have already refactored the main YOLO series solutions into a unified format and are conducting extensive experiments. As for supporting segmentation, our refactoring solution is actually very similar to YOLOv8. You can modify the dataloader to read segmentation data and then reload a segmentation detection head to complete the segmentation training task (these are readily available implementations in YOLOv8, so it shouldn't be too difficult to modify)
 Feel free to ask any question!

**Comment by jie311** [comment]
想问一下基于yolov8的ssod完成了吗

**Comment by DaMEi7** [comment]
> Hello, due to our limited development resources, I will provide a scheduling update for your two requirements. Currently, we are working on semi-supervised anchor-free detection, as you can see, we have already refactored the main YOLO series solutions into a unified format and are conducting extensive experiments. As for supporting segmentation, our refactoring solution is actually very similar to YOLOv8. You can modify the dataloader to read segmentation data and then reload a segmentation detection head to complete the segmentation training task (these are readily available implementations in YOLOv8, so it shouldn't be too difficult to modify) Feel free to ask any question!

请问yolov8的半监督代码完成了吗
